name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.API_CETICY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@192.162.69.37 << 'EOF'
          cd node-ceticy/
          git pull origin main
          docker compose down
          docker compose -f compose-prod.yml up -d --build
          EOF
