name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  typescript-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set test DB env
        run: |
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_USER=test" >> $GITHUB_ENV
          echo "DB_PASSWORD=test" >> $GITHUB_ENV
          echo "DB_NAME=testdb" >> $GITHUB_ENV

      - name: Generate a coverage report
        run: npm run coverage --if-present

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run TypeScript compiler
        run: npm run build --if-present
        env:
          NODE_ENV: test