name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  typescript-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript compiler
        run: npm run build --if-present
        env:
          NODE_ENV: test